name: bindings_generation
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: 'devel'

      - name: Generate
        run: nimble generate
