name: bindings_generation
on:
  push:
    paths:
      - 'generator/third_party/**'
  workflow_dispatch:

jobs:
  wgpu-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: 'recursive'
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: 'devel'
      
      # Install rust to build wgpu-native
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      
      - name: Generate bindings
        run: nimble generate_wgpu -y
      
      - name: Update repository bindings
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'src/nimgpu/*'
          message: 'Automatic wgpu-native bindings update'
          push: true
  dawn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: 'recursive'
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: 'devel'
      
      # Install depot tools to build dawn
      - name: Install depot tools
        uses: newkdev/setup-depot-tools@v1.0.1

      - name: Generate bindings
        run: nimble generate_dawn -y
      
      - name: Update repository bindings
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'src/nimgpu/*'
          message: 'Automatic dawn bindings update'
          push: true
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: 'recursive'
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: 'devel'
      
      - name: Generate bindings
        run: nimble generate_emscripten -y
      
      - name: Update repository bindings
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'src/nimgpu/*'
          message: 'Automatic dawn bindings update'
          push: true