name: bindings_generation
on:
  push:
    paths:
      - 'generator/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'devel'
      
      #Install rust to build wgpu-native
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Generate bindings
        run: nimble generate -y
      
      - name: Update repository bindings
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'src/nimgpu/*'
          message: 'Automatic bindings update'
          push: true
